Repository kookmin-sw/capstone-2025-30, pull requests merged in 2025-05, with the labels that each got.

#108 Server/feat/get chatroom list
  proto/message.proto
  proto/service.proto
  server/gen/message.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/internal/pkg/database/mongodb/message/notification.go
  server/internal/pkg/database/structure/message.go
  server/internal/pkg/grpc/message.go
  server/internal/pkg/rest/initialize.go
  server/internal/pkg/rest/message.go
  server/proto/message.proto
  server/proto/service.proto
Labels: enhancement

#113 Server/feat/update order completed
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/grpc/order.go
Labels: enhancement

#117 Server/feat/korean text send
  server/cmd/myapp/main.go
  server/internal/pkg/grpc/handler.go
  server/internal/pkg/grpc/inquiry.go
  server/internal/pkg/utils/aiinitialize.go
  server/internal/pkg/utils/struct.go
  server/internal/pkg/websocket/handler.go
  server/internal/pkg/websocket/receivemessage.go
  server/internal/pkg/websocket/sendmessage.go
Labels: enhancement

#118 [server/refactor] rest-body-to-param : rest api request body -> query…
  server/internal/pkg/rest/message.go
Labels: refactor

#119 [server/feat] korean-text-send-4 : 관리자 웹 대화창에서 "문의사항" keyword 가 들어간 메…
  server/internal/pkg/websocket/receivemessage.go
Labels: enhancement

#121 Server/refactor/error handling - store, menu, order 에러 핸들링 및 유효성 검사 통일
  proto/error.proto
  server/gen/error.pb.go
  server/gen/menu.pb.go
  server/gen/order.pb.go
  server/gen/store.pb.go
  server/internal/pkg/database/mongodb/menu/crud.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/mongodb/store/crud.go
  server/internal/pkg/grpc/menu.go
  server/internal/pkg/grpc/order.go
  server/internal/pkg/grpc/store.go
  server/internal/pkg/rest/initialize.go
  server/internal/pkg/rest/menu.go
  server/internal/pkg/rest/order.go
  server/internal/pkg/rest/store.go
  server/internal/pkg/utils/errormapper.go
  server/proto/error.proto
Labels: enhancement, refactor

#124 Server/feat/counter app quick response no
  proto/error.proto
  proto/inquiry.proto
  proto/service.proto
  server/gen/error.pb.go
  server/gen/inquiry.pb.go
  server/gen/menu.pb.go
  server/gen/order.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/gen/store.pb.go
  server/internal/pkg/grpc/inquiry.go
  server/internal/pkg/websocket/receivemessage.go
  server/proto/error.proto
  server/proto/inquiry.proto
  server/proto/service.proto
Labels: enhancement

#127 Server/feat/get chatroom list 2
  server/internal/pkg/database/mongodb/message/notification.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/structure/message.go
  server/internal/pkg/grpc/message.go
  server/internal/pkg/grpc/order.go
  server/internal/pkg/rest/message.go
Labels: bug, enhancement

#133 Server/feat/ai response confidence
  proto/error.proto
  server/gen/error.pb.go
  server/internal/pkg/grpc/inquiry.go
  server/proto/error.proto
Labels: enhancement

#143 Server/feat/menu 카테고리 우선순위 변경
  server/gen/all_predict_sign.pb.go
  server/gen/all_predict_sign_grpc.pb.go
  server/gen/error.pb.go
  server/gen/inquiry.pb.go
  server/gen/menu.pb.go
  server/gen/message.pb.go
  server/gen/order.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/gen/store.pb.go
  server/gen/test.pb.go
  server/internal/pkg/database/mongodb/menu/crud.go
Labels: enhancement

#141 Server/fix/order 주문 생성 시 메뉴 존재 여부 검증, DineIn JSON Binding 오류 수정
  server/internal/pkg/grpc/order.go
  server/internal/pkg/rest/order.go
Labels: bug

#175 Server/feat/fast inquiry key world add
  server/internal/pkg/database/mongodb/collections.go
  server/internal/pkg/database/mongodb/fastinquiry/crud.go
  server/internal/pkg/database/structure/fastinquiry.go
  server/internal/pkg/websocket/receivemessage.go
Labels: enhancement

#180 Server/feat/inquiry finished
  proto/inquiry.proto
  proto/service.proto
  server/gen/all_predict_sign.pb.go
  server/gen/all_predict_sign_grpc.pb.go
  server/gen/error.pb.go
  server/gen/inquiry.pb.go
  server/gen/menu.pb.go
  server/gen/message.pb.go
  server/gen/order.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/gen/store.pb.go
  server/gen/test.pb.go
  server/internal/pkg/database/mongodb/message/notification.go
  server/internal/pkg/grpc/inquiry.go
  server/internal/pkg/rest/initialize.go
  server/internal/pkg/rest/inquiry.go
  server/proto/inquiry.proto
  server/proto/service.proto
Labels: enhancement
