Repository kookmin-sw/capstone-2025-30, pull requests merged in 2025-04, with the labels that each got.

#20 Server/feat/gin initailize api key middleware setting
  server/cmd/myapp/main.go
  server/internal/pkg/rest/AddTestStruct.go
  server/internal/pkg/rest/handler.go
Labels: enhancement

#25 Server/feat/add nginx reverse proxy
  server/internal/pkg/grpc/interceptor.go
  server/internal/pkg/websocket/handler.go
  server/nginx.conf
Labels: enhancement

#34 Server/feat/add docker build
  server/Dockerfile
  server/Makefile
  server/nginx.conf
  server/proto/test.proto
Labels: enhancement

#49 Server/feat/counter app grpc stream
  proto/error.proto
  proto/inquiry.proto
  proto/service.proto
  server/gen/error.pb.go
  server/gen/inquiry.pb.go
  server/gen/predict_sign.pb.go
  server/gen/predict_sign_grpc.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/internal/pkg/database/mongodb/auth/store_auth.go
  server/internal/pkg/grpc/handler.go
  server/internal/pkg/grpc/inquiry.go
  server/proto/error.proto
  server/proto/inquiry.proto
  server/proto/predict_sign.proto
  server/proto/service.proto
Labels: enhancement

#56 [Server/feat/menu api : Menu 관련 gRPC + REST 구현
  proto/menu.proto
  proto/service.proto
  server/gen/menu.pb.go
  server/gen/predict_sign.pb.go
  server/gen/predict_sign_grpc.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/internal/pkg/database/mongodb/collections.go
  server/internal/pkg/database/mongodb/menu/crud.go
  server/internal/pkg/database/structure/menu.go
  server/internal/pkg/grpc/handler.go
  server/internal/pkg/grpc/menu.go
  server/internal/pkg/rest/initialize.go
  server/internal/pkg/rest/menu.go
  server/proto/menu.proto
  server/proto/service.proto
Labels: enhancement

#60 [Server/feat] : mongo db index
  server/internal/pkg/database/mongodb/indexes.go
  server/internal/pkg/database/mongodb/main.go
Labels: enhancement

#61 Server/feat/order api : Order 관련 gRPC + REST 구현
  proto/order.proto
  proto/service.proto
  server/gen/order.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/internal/pkg/database/mongodb/collections.go
  server/internal/pkg/database/mongodb/menu/crud.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/mongodb/order/number.go
  server/internal/pkg/database/structure/order.go
  server/internal/pkg/grpc/order.go
  server/internal/pkg/rest/initialize.go
  server/internal/pkg/rest/order.go
  server/proto/order.proto
  server/proto/service.proto
Labels: enhancement

#63 Server/refactor/store_code_validation : StoreCode 검증 로직 구현 및 추가
  proto/error.proto
  server/gen/error.pb.go
  server/internal/pkg/database/mongodb/menu/crud.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/mongodb/store/validator.go
  server/internal/pkg/database/structure/menu.go
  server/internal/pkg/database/structure/order.go
  server/internal/pkg/grpc/inquiry.go
  server/internal/pkg/grpc/menu.go
  server/internal/pkg/grpc/order.go
  server/internal/pkg/rest/menu.go
  server/proto/error.proto
Labels: refactor

#86 Update server.yml
  .github/workflows/server.yml
Labels: bug

#87 Server/feat/order info message
  proto/error.proto
  server/gen/error.pb.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/structure/message.go
  server/internal/pkg/grpc/inquiry.go
  server/internal/pkg/grpc/order.go
  server/proto/error.proto
Labels: enhancement, refactor

#93 Server/feat/menu - CreateMenu 시 중복 등록 방지 기능 추가
  proto/error.proto
  server/gen/error.pb.go
  server/internal/pkg/database/mongodb/menu/crud.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/mongodb/order/number.go
  server/internal/pkg/grpc/menu.go
  server/internal/pkg/grpc/order.go
  server/proto/error.proto
Labels: enhancement

#91 Server/refactor/store - storeCode 제거 및 ObjectID 기반 CRUD 리팩토링 및 기능 추가
  proto/error.proto
  server/gen/all_predict_sign.pb.go
  server/gen/all_predict_sign_grpc.pb.go
  server/gen/error.pb.go
  server/gen/inquiry.pb.go
  server/gen/menu.pb.go
  server/gen/order.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/gen/store.pb.go
  server/gen/test.pb.go
  server/internal/pkg/database/mongodb/menu/crud.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/database/mongodb/order/number.go
  server/internal/pkg/database/mongodb/store/crud.go
  server/internal/pkg/grpc/menu.go
  server/internal/pkg/grpc/order.go
  server/internal/pkg/grpc/store.go
  server/proto/error.proto
Labels: enhancement, refactor

#103 Server/feat/get chatroom messages
  proto/inquiry.proto
  proto/message.proto
  proto/service.proto
  server/gen/all_predict_sign.pb.go
  server/gen/all_predict_sign_grpc.pb.go
  server/gen/error.pb.go
  server/gen/inquiry.pb.go
  server/gen/menu.pb.go
  server/gen/message.pb.go
  server/gen/order.pb.go
  server/gen/service.pb.go
  server/gen/service_grpc.pb.go
  server/gen/store.pb.go
  server/gen/test.pb.go
  server/internal/pkg/database/mongodb/message/crud.go
  server/internal/pkg/grpc/message.go
  server/internal/pkg/rest/initialize.go
  server/internal/pkg/rest/message.go
  server/proto/inquiry.proto
  server/proto/message.proto
  server/proto/service.proto
Labels: enhancement

#107 Server/feat/connect chat by ordernum
  proto/message.proto
  server/gen/message.pb.go
  server/internal/pkg/database/mongodb/message/crud.go
  server/internal/pkg/database/mongodb/order/crud.go
  server/internal/pkg/grpc/inquiry.go
  server/internal/pkg/grpc/message.go
  server/internal/pkg/grpc/order.go
  server/proto/message.proto
Labels: enhancement
